### ISSUE TITLE
verify-ssl only set for true value

### ISSUE THREAD

**Issue by alkuzad** [logstash-plugins/logstash-output-http#41] opened 2016-06-22 10:16 UTC
``` ruby
@ssl_certificate_validation = @verify_ssl if @verify_ssl
```

Has to be changed to something that checks for both true and false:

``` ruby
@ssl_certificate_validation = @verify_ssl if [TrueClass,FalseClass].include?(@verify_ssl.class)
```

`ssl_certificate_validation` seems to be ignored and not set properly (adding print to mixin-http-output shows that it does not change value of ssl verify)

**Comment by alkuzad** [comment] 2016-06-24 10:11
correction: this issue of course is only valid for LS lower than 5.0

**Comment by amulyas** [comment] 2016-10-12 22:12
I am setting     ssl_certificate_validation => false 
but still getting {:timestamp=>"2016-10-12T15:10:42.739000-0700", :message=>"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target", :url=>"https://input-prd-p-aasdasd.cloud.splunk.com:8088/services/collector/event", :method=>:post, :body=>"{ \"event\", \"tasdaskdj\" }", :headers=>{"Authorization"=>"Splunk a-42ED-8F4sdasdas1-4399FC4CC2B6", "Content-Type"=>"text/plain"}, :class=>"Man

**Comment by amulyas** [comment] 2016-10-12 22:12
@alkuzad

**Comment by kares** [comment] 2022-02-03 06:36
Going to close this one as a duplicate of https://github.com/logstash-plugins/logstash-output-http/issues/21#issuecomment-1028645486 there's a new option supported since https://github.com/logstash-plugins/logstash-output-http/pull/126

**Closed by kares** 2022-02-03 06:36 UTC
