### ISSUE TITLE
PKIX path building failed:

### ISSUE THREAD

**Issue by harbris** [logstash-plugins/logstash-output-http#29] opened 2015-11-16 13:53 UTC
logstash 2.0 version

I want to request https server.

however, it doesn't work 

AlthoughI  set config ssl_certificate_validation is false.

it has been occur "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target "

please, let me know that how does ploblem solve

thank you

**Comment by amulyas** [comment] 2016-10-12 22:14
@harbris were you able to find fix for this or able to workaround this ?

**Comment by kares** [comment] 2022-02-03 06:38
closing as duplicate of https://github.com/logstash-plugins/logstash-output-http/issues/41
the issue is resolved with https://github.com/logstash-plugins/logstash-output-http/pull/126

**Closed by kares** 2022-02-03 06:38 UTC
